# 我是一级标题
## 我是二级标题
### 我是三级标题

我是**粗体字**  
我是*斜体字*  
我被~~删除了~~  

# 我也是一级标题

- 我是列表的第一行
- 我是列表的第二行 
- 我是列表的第三行
1. 我是列表的第一行
2. 我是列表的第三行
3. 我才是列表的第三行

[B站课堂](https://www.bilibili.com/cheese/play/ep124472?csource=common_myclass_purchasedlecture_null&spm_id_from=333.874.selfDef.mine_paid_list)

> 孤舟蓑笠翁  
独钓寒江雪

我们通过`pandas`来完成数据清洗

这是一个公式：$y=x+3$

下面是一个独占一行的公式：$$y=x+3$$

$$x=y$$ $$x-y$$ $$x\times y$$ $$x\div y$$ $$x^3$$ $$H_2SO_3$$ $$S_{input}$$ 
$$S^2=\frac{1}{n}\sum_{i=1}^n(X_i-\overline X)^2$$ $$\sqrt[n]{x+y}$$

# Numpy

In [1]:
import numpy as np
print(np.__version__)

1.26.4


## 创建数组

### 属性
`.shape`各个维度里元素的个数  
`.ndim`数组（矩阵）的维度  
`.size`元素里的总个数  
`.dtype`数组元素的类型，比如说`int64`就是整数且比特长度是64  
### 方法  
`np.array(...)`手动传入元素创建数组  
`np.zeros(...)`  
`np.ones(...)`  
注：数字后面带小数点是因为数字的类型是浮点数  
`np.arange(...)`

#### 实践

创建一个变量名为 arr1 的一维数组，里面的元素为整数6、2、-7、2、8、-2、1。创建后输出arr1

In [2]:
arr1 = np.array([6,2,-7,2,8,-2,1])
print(arr1)

[ 6  2 -7  2  8 -2  1]


创建一个变量名为 arr2 的二维数组，里面的元素为以下两个数组:由整数1、3、5组成的一维数组，以及由整数2、4、6组成的一维数组。创建后输出arr2。

In [3]:
arr2 = np.array([[1,3,5],[2,4,6]])
print(arr2)

[[1 3 5]
 [2 4 6]]


分别打印 arr1 和 arr2 的维度、形状、元素数量、元素类型

In [4]:
print(arr1.ndim,arr1.dtype)
print(arr1.shape)
print(arr1.size)

1 int32
(7,)
7


In [5]:
arr_all_0 = np.zeros(6)
print(arr_all_0)

[0. 0. 0. 0. 0. 0.]


In [6]:
arr_all_1 = np.ones(6)
print(arr_all_1)

[1. 1. 1. 1. 1. 1.]


In [7]:
arr_even = np.arange(10,21,2)
print(arr_even)

[10 12 14 16 18 20]


## 数组常用操作

`np.conatenate([array1,array2])` 用于连接数组  
`np.sort(array1)` NumPy的sort函数，不改变原始数组  
`array1.sort()` NumPy的sort方法，改变原始数组  
`array1[index]` 用索引获得某一元素  
`array1[begin:end]` 切片（不包括最后那个元素）  
拓展 `array1[:end]`,`array1[begin:]`和`array1[:]`

#### 数组运算

array1 + array2  
array1 - array2  
array1 * array2  
array1 / array2  
对应元素直接进行运算  

array1 * b 数组与单个数字运算，广播机制  
`array1.max()`  
`array1.min()`  
`array1.sum()`  
`array1.mean()`  聚合操作

#### 条件筛选

`array1[array1的条件语句]` 返回由满足条件的元素组成的数组  
如`array1[array1 > 5]` 返回数组中大于5的元素组成的一个数组

`array1[(条件1）&（条件2）](|和~)` 为逻辑运算，分别表示“与”“或”“非”

# Pandas

In [8]:
import pandas as pd

## 创建Series

`pd.Series([x,x,x])` 注意S要大写  
`pd.Series({标签：值})` 直接传入字典

In [9]:
print(pd.Series([11,12,13]))

0    11
1    12
2    13
dtype: int64


### 获得Series的元素和索引

`.values`获得元素  
`.index`获得索引

### 索引和切片

索引可自定义（标签）  
`pd.Series([],index = [])`

切片操作和python列表一样  
如果要获取多个元素，使用切片

两种索引取值的方法  
用标签索引 `s1.loc[]`  
用位置索引 `s1.iloc[]`
注意！位置索引（数字）不包含结束值，而标签索引包含

### 修改Series里的值

`s.iloc/loc[索引] = xxx` "i"开头指的是位置索引，否则就是标签索引

### 条件筛选

`series[series条件语句]` 返回满足条件的Series元素组成的Series  
与   或   非  
&    |    ~

## Series操作

### Series运算  
`Series1 + Series2` 将两Series的共同元素对应相加，一个Series独有的元素变成NaN，返回一个并集，索引自动对齐  
`Series1.add(s2, fill_value=0)` 给NaN设置一个默认值0

统计学运算  
`s1.max()`  
`s1.min()`  
`s1.sum()`  
`s1.mean()`   
一键算统计学指标  
`s1.describe()`

广播机制  
`s1 * a`  
`s1.apply(函数)` 将函数分别运用于各个元素，返回一个新的Series，不改变原Series的值（这里也可以使用匿名函数）

## DataFrame

"由Series组成的字典，键是列名，值是Series"

### 创建DataFrame

`pd.DataFrame({列名:Series(或者是列表),列名:Series(或者是列表)})` 传入字典  
index默认是从0开始的数字，如果传入的Series的index是标签，则DataFrame的index也会变为对应的标签  
也可以是字典嵌套字典的方法传入（因为Series可以由传入一个字典创建），最外层的键仍然对应各个列名（最内层的字典是Series，最外层的字典是DF）

### 获取DataFrame的索引和列名

`df1.index` 索引  
`df1.columms` 列名  
`df1.values` 值  

### 对DataFrame进行转置  
`df1.T` 把原来的行变成列，把列变成行

### 提取DataFrame的列  
`df1[列名]` 返回索引加值组成的Series（和字典类似）  
或者用属性 `df1.列名` 但是如果列名里面由特殊符号或者运算符就不能用此方法  
如果想提取多个列的话，可以在[]中将要提取的列名写成一个集合（不是切片）  
如 `df1[["学号,"成绩"]]` 返回一个DataFrame

### 提取DataFrame里的行  
`df1.loc[索引（行名）]`  返回由列名为索引、同一行值所构成的Series（因为提取行相当于Series里面的“索引取值”，所以用loc或iloc）  
提取多个行，使用行名的切片或者位置切片，同样，位置切片不包含结束值，而标签包含。  
如果想取特定的行，传入的参数写成列表。如`df1.loc[["小明","小丽"]]`

### 提取DataFrame里的特定元素  
`df1.loc[行名,列名]` 或 `df1.iloc[行的位置索引,列的位置索引]`

### 提取部分DataFrame  
`df1.loc[行名的切片,列名的切片]` 或 `df1.iloc[行的位置索引切片,列的位置索引切片]`  
位置索引不包含结束值，这里的切片不是列表了，如`df1.loc[:,"考试1","考试3"]`

### 条件筛选DataFrame的行  
"行是一个实例，列是实例的属性"
`df1[df1[列名] > 80(条件)]` DataFrame的列是Series类型,Series和条件结合，会返回由布尔值组成的Series,DataFrame保留True的行，返回一个满足条件的DataFrame

与或非同Series  
如`df1[(df1["成绩"] > 80) & (df1["班级"] == "一班")]`

### 获取DataFrame的前N行  
`df1.head()` 默认返回前5行  
`df1.head(n)` 返回前n行

练习

In [10]:
name = pd.Series(["小陈","小李","小王","小张"],index = ["001","002","003","004"])
gender = pd.Series(["女","女","男","男"],index = ["004","003","002","001"])
height = pd.Series([172,168,180,175],index = ["001","002","003","004"])

In [11]:
students = pd.DataFrame({"姓名":name, "性别":gender, "身高":height})
students

姓名 性别   身高
001  小陈  男  172
002  小李  男  168
003  小王  女  180
004  小张  女  175

In [12]:
print(students.index,students.columns)

Index(['001', '002', '003', '004'], dtype='object') Index(['姓名', '性别', '身高'], dtype='object')


In [13]:
students.T

001  002  003  004
姓名   小陈   小李   小王   小张
性别    男    男    女    女
身高  172  168  180  175

In [14]:
students["身高"]

001    172
002    168
003    180
004    175
Name: 身高, dtype: int64

In [15]:
students[["性别","身高"]]

性别   身高
001  男  172
002  男  168
003  女  180
004  女  175

In [16]:
students.loc["002"]

姓名     小李
性别      男
身高    168
Name: 002, dtype: object

In [17]:
students.loc["002":"004"]

姓名 性别   身高
002  小李  男  168
003  小王  女  180
004  小张  女  175

In [18]:
students.loc[["002","004"],["姓名","身高"]]

姓名   身高
002  小李  168
004  小张  175

In [19]:
students.loc[["002","004"]]

姓名 性别   身高
002  小李  男  168
004  小张  女  175

In [20]:
students[(students["身高"] > 165) & (students["性别"] == "女")]

姓名 性别   身高
003  小王  女  180
004  小张  女  175

In [21]:
students.head()

姓名 性别   身高
001  小陈  男  172
002  小李  男  168
003  小王  女  180
004  小张  女  175

### 更新（创建）DataFrame的一列值  
`df1[列名] = Series (或者Python列表)` 如果原Series里面有标签索引，那么新的Series里面也要有index属性，否则所有无法对齐的地方就会变成一个NaN。  
如果是列表就不用，会自动对齐。  
如果列名不存在，则会自动创建一个列，并以其为列名。

### 更新（创建）DataFrame的一行值  
`df1.loc[索引(行名)] = Series (或者Python列表)` 需要把Series的index标签与列名相对应，列表则会自动对齐  
注意：创建行只能用loc，用iloc会报错

### 删除DataFrame的行或者列  
删除一行 `df1.drop(索引(行名))`  
删除多行 `df1.drop(列表(包含多个标签索引))`  
注意，drop并不会改变原始DataFrame，如果想要改变原始数据，将df1.drop[]重新赋值给df1  
删除一列 `df1.drop(列名, axis = 1)`   
注：axis = 1，沿着列名横向进行操作；axis = 0，沿着索引纵向进行操作。（判断axis是0还是1，关键看你的操作对象，删除列，操作对象（传入参数）是列名，要从列名处横向照，axis=1，而在后面df求平均值时，操作对象是元素，axis=1，返回Series和索引对应）  
删除多列 `df1.drop(列表, axis = 1)`

### DataFrame和DataFrame操作  
`df1.add(df2, fill_value = 0)` 相加   
`df1.sub(df2, fill_value = 0)` 相减  
`df1.div(df2, fill_value = 0)` 相除  
`df1.mul(df2, fill_value = 0)` 相乘

### DataFrame和Series操作  
将Series的索引和DataFrame的列名对齐，应用到对应列下DataFrame的每一行上

练习

In [22]:
students = pd.DataFrame({"001":{"姓名":"小陈","考试1":85,"考试2":95,"考试3":92},
                         "002":{"姓名":"小李","考试1":91,"考试2":92,"考试3":94},
                         "003":{"姓名":"小王","考试1":86,"考试2":81,"考试3":89},
                         "004":{"姓名":"小张","考试1":79,"考试2":88,"考试3":92},
                         "005":{"姓名":"小赵","考试1":90,"考试2":80,"考试3":98},
                         "006":{"姓名":"小周","考试1":83,"考试2":95,"考试3":90},})
students = students.T
students

姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  88  92
005  小赵  90  80  98
006  小周  83  95  90

In [23]:
students["考试4"] = [72, 69, 79 ,83, 82, 76]
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  88  92   83
005  小赵  90  80  98   82
006  小周  83  95  90   76

In [24]:
students.loc["007"] = ["小杨", 79, 82, 81, 69]
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  88  92   83
005  小赵  90  80  98   82
006  小周  83  95  90   76
007  小杨  79  82  81   69

In [25]:
abcc = students.drop(["006", "007"])
abcc

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   72
002  小李  91  92  94   69
003  小王  86  81  89   79
004  小张  79  88  92   83
005  小赵  90  80  98   82

In [26]:
aabc = students.drop(["考试2", "考试4"], axis = 1)
aabc

姓名 考试1 考试3
001  小陈  85  92
002  小李  91  94
003  小王  86  89
004  小张  79  92
005  小赵  90  98
006  小周  83  90
007  小杨  79  81

In [27]:
bonus = pd.Series({"考试1":2,"考试2":3,"考试3":2,"考试4":5})
aaaaa = students[["考试1","考试2","考试3","考试4"]] + bonus
aaaaa

考试1 考试2  考试3  考试4
001  87  98   94   77
002  93  95   96   74
003  88  84   91   84
004  81  91   94   88
005  92  83  100   87
006  85  98   92   81
007  81  85   83   74

In [28]:
students["考试4"] = students["考试4"] + 10
students

姓名 考试1 考试2 考试3  考试4
001  小陈  85  95  92   82
002  小李  91  92  94   79
003  小王  86  81  89   89
004  小张  79  88  92   93
005  小赵  90  80  98   92
006  小周  83  95  90   86
007  小杨  79  82  81   79

### DataFrame的统计方法  
`df1.mean()` 默认沿axis = 0操作，返回的Series和列名对应。，求列的均值   
`df1.mean(axis = 1)` 沿axis = 1操作，返回Series和索引对应，求行的均值  
`df1.apply(传入一个函数, axis =0/1)` 将函数应用于行或者列（默认是列），若是列，返回一个Series以列名为索引，若是行，返回一个Series以行名（df的索引）为索引
`df1.applymap(传入一个函数)` 将函数应用于每个元素上，返回一个新的df，不改变原df  
`df1.describe()` 得到各列的统计信息，会自动忽略掉所有非数字的列  
`df1[列名] = df1[列名].astype('int')` 可以更新使得每一列类型为数字，常常在decribe方法之前使用

In [29]:
students = pd.DataFrame({"001":{"姓名":"小陈","考试1":85,"考试2":95,"考试3":92},
                         "002":{"姓名":"小李","考试1":91,"考试2":92,"考试3":94},
                         "003":{"姓名":"小王","考试1":86,"考试2":81,"考试3":89},
                         "004":{"姓名":"小张","考试1":79,"考试2":88,"考试3":92},
                         "005":{"姓名":"小赵","考试1":90,"考试2":80,"考试3":98},
                         "006":{"姓名":"小周","考试1":83,"考试2":95,"考试3":90},})
students = students.T
students

姓名 考试1 考试2 考试3
001  小陈  85  95  92
002  小李  91  92  94
003  小王  86  81  89
004  小张  79  88  92
005  小赵  90  80  98
006  小周  83  95  90

In [30]:
socres = students.loc[:,"考试1":"考试3"]
student_average = pd.DataFrame({"姓名":students["姓名"],"平均分":socres.mean
                                (axis = 1)})
student_average

姓名        平均分
001  小陈  90.666667
002  小李  92.333333
003  小王  85.333333
004  小张  86.333333
005  小赵  89.333333
006  小周  89.333333

In [32]:
students.loc[:,"考试1":"考试3"].apply(lambda x: np.sort(x)[-2])

考试1    90
考试2    95
考试3    94
dtype: int64

In [36]:
def get_grade(score):
    if score >= 95:
        return "A+"
    elif score >= 90:
        return "A"
    elif score >= 85:
        return "B+"
    elif score >= 80:
        return "B"
    elif score >= 75:
        return "C+"
    else:
        return "C"
grades = students.loc[:,"考试1":"考试3"].applymap(get_grade)
grades

C:\Users\15541\AppData\Local\Temp\ipykernel_4756\807576231.py:14: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  grades = students.loc[:,"考试1":"考试3"].applymap(get_grade)


考试1 考试2 考试3
001  B+  A+   A
002   A   A   A
003  B+   B  B+
004  C+  B+   A
005   A   B  A+
006   B  A+   A

In [40]:
students.describe()

姓名  考试1  考试2  考试3
count    6    6    6    6
unique   6    6    5    5
top     小陈   85   95   92
freq     1    1    2    2

In [42]:
students["考试1"] = students["考试1"].astype('int')
students["考试2"] = students["考试2"].astype('int')
students["考试3"] = students["考试3"].astype('int')
students.describe()

考试1        考试2        考试3
count   6.000000   6.000000   6.000000
mean   85.666667  88.500000  92.500000
std     4.457204   6.715653   3.209361
min    79.000000  80.000000  89.000000
25%    83.500000  82.750000  90.500000
50%    85.500000  90.000000  92.000000
75%    89.000000  94.250000  93.500000
max    91.000000  95.000000  98.000000

# 数据分析流程

## 获取数据

![公开数据集](https://img.picui.cn/free/2025/05/31/683ac22195fec.jpg)

### 获得公开数据的方式有  
- 直接下载
- 通过爬虫获取数据，且数据需要额外解析（注意红线）
- 通过API获取数据，数据易于提取和使用

## 常见数据格式

### JSON (JavaScript Object Notation)

注：文件名后缀是计算机打开该文件的方式。例：如果原是txt文件，修改后缀为mp3，计算机会用mp3程序（音乐播放器）来打开该文件，从而产生错误。但是修改后缀并不改变实际格式！我们聊文件格式，不仅聊后缀，还聊文件内容实际的格式规则。

用API获取数据，很多时候数据都是以JSON格式返回的

### JSON的数据结构  
`JSON对象`和`JSON数组`，可以分别转换成Python字典和列表

![JSON对象](https://img.picui.cn/free/2025/05/31/683ac61bd5d3b.png)  
以花括号开头和结尾

![JSON数组](https://img.picui.cn/free/2025/05/31/683ac6c7a0ac4.png)  
以中括号开头和结尾

JSON数据里面只能用字符串作为键，且必须用双引号

### 类型  
- 字符串  `"str"` （注意双引号）
- 数字  `31`
- 布尔值  `true/false` （注意小写开头）
- 数组  `["hi",7]`
- 对象  `{"age":25}`
- 空值  `null`  
支持嵌套

## 读取数据  
使用pandas库进行

函数`pd.read_json(传入文件路径)`用于读JSON文件，返回DF  
read_json函数会帮助完成文件读取、JSON解析、转成DataFrame的全流程

In [3]:
import pandas as pd
file1 = pd.read_json(r"C:\Users\15541\Desktop\数据分析\数据集\cell_phones_survey.json")
file1

questionType        asin    answerTime    unixTime  \
0       yes/no  1466736038   Mar 8, 2014  1394265600   
1       yes/no  1466736038  Jan 29, 2015  1422518400   
2       yes/no  1466736038  Nov 30, 2014  1417334400   
3   open-ended  1466736038   Nov 3, 2014  1415001600   
4       yes/no  1466736038   Oct 2, 2014  1412233200   
5   open-ended  1466736038  Sep 11, 2014  1410418800   
6       yes/no  1621911888  Dec 13, 2013  1386921600   

                                            question answerType  \
0                         Is there a SIM card in it?          Y   
1  Is this phone new, with 1 year manufacture war...          ?   
2  can in it be used abroad with a different carr...          Y   
3                      What is the warranty on this?        NaN   
4  Does this phone use the regular Sim card (the ...          ?   
5  how much time you need to send me this product...        NaN   
6                                    Is it unlocked?          Y   

                                              answer  
0  Yes. The Galaxy SIII accommodates a micro SIM ...  
1  It is new but I was not able to get it activat...  
2                                                Yes  
3                                        No warranty  
4                                  it takes mini sim  
5  If you choose expedited shipping you will have...  
6                                                yes

### CSV (Comma-Separated Values)
CSV是纯文本，第一行大部分是表头，即列名；每一行数据独占一行，每一行里值的数量相同，逗号分隔符数量相同。  
CSV可以用Excel打开并编辑，同时可以将Excel编辑好的表格导出为CSV  
注意！当一个CSV文件大小有1G以上时，不要用Excel打开！！！反之用代码编辑器或者文本编辑器打开，最好是：用代码读取，转换成DataFrame，然后用pandas方法，想看几行就看几行，如`df1.heads()`

### 用代码读取和解析CSV文件

函数`pd.read_csv(传入文件路径)`读取CSV文件，返回DF  
如果csv第一行不是表头，则将header设置为None，即`pd.read_csv(xxx,header=None)`  
如果想指定一列作为DF的标签索引，设置index_col参数，即`pd.read_csv(xxx, index_col=列名)`

In [5]:
import pandas as pd
file2 = pd.read_csv(r"C:\Users\15541\Desktop\数据分析\数据集\fifa_players.csv",index_col="player_id")
file2.head()

C:\Users\15541\AppData\Local\Temp\ipykernel_20804\2118650158.py:2: DtypeWarning: Columns (108) have mixed types. Specify dtype option on import or set low_memory=False.
  file2 = pd.read_csv(r"C:\Users\15541\Desktop\数据分析\数据集\fifa_players.csv",index_col="player_id")


player_url  fifa_version  \
player_id                                                                   
158023                   /player/158023/lionel-messi/150002            15   
20801      /player/20801/c-ronaldo-dos-santos-aveiro/150002            15   
9014                       /player/9014/arjen-robben/150002            15   
41236               /player/41236/zlatan-ibrahimovic/150002            15   
167495                   /player/167495/manuel-neuer/150002            15   

           fifa_update fifa_update_date         short_name  \
player_id                                                    
158023               2       2014-09-18           L. Messi   
20801                2       2014-09-18  Cristiano Ronaldo   
9014                 2       2014-09-18          A. Robben   
41236                2       2014-09-18     Z. Ibrahimović   
167495               2       2014-09-18           M. Neuer   

                                     long_name player_positions  overall  \
player_id                                                                  
158023          Lionel Andrés Messi Cuccittini               CF       93   
20801      Cristiano Ronaldo dos Santos Aveiro           LW, LM       92   
9014                              Arjen Robben       RM, LM, RW       90   
41236                       Zlatan Ibrahimović               ST       90   
167495                      Manuel Peter Neuer               GK       90   

           potential    value_eur  ...   cdm   rdm   rwb    lb   lcb    cb  \
player_id                          ...                                       
158023            95  100500000.0  ...  62+3  62+3  62+3  54+3  45+3  45+3   
20801             92   79000000.0  ...  63+3  63+3  63+3  57+3  52+3  52+3   
9014              90   54500000.0  ...  64+3  64+3  64+3  55+3  46+3  46+3   
41236             90   52500000.0  ...  65+3  65+3  61+3  56+3  55+3  55+3   
167495            90   63500000.0  ...  40+3  40+3  36+3  36+3  38+3  38+3   

            rcb    rb    gk                                    player_face_url  
player_id                                                                       
158023     45+3  54+3  15+3  https://cdn.sofifa.net/players/158/023/15_120.png  
20801      52+3  57+3  16+3  https://cdn.sofifa.net/players/020/801/15_120.png  
9014       46+3  55+3  14+3  https://cdn.sofifa.net/players/009/014/15_120.png  
41236      55+3  56+3  17+3  https://cdn.sofifa.net/players/041/236/15_120.png  
167495     38+3  36+3  87+3  https://cdn.sofifa.net/players/167/495/15_120.png  

[5 rows x 109 columns]

由上面的df可见，当列数量非常多的时候，中间的有些列会被自动省略（默认20列）  
使用`pd.set_option("display.max_columns",希望列数上限)`来提高看到的列数上限

当某一个值长度太长，也会被省略（默认50）  
使用`pd.set_option("display.max_colwidth",希望看值的长度上限)`来提高看到的值的长度上限

想看到开头几行，使用`.head(行数)`  
想看到结尾几行，使用`.tail(行数)`  
什么参数都不传入，默认返回5行

想快速了解df，使用`.info()`方法

想了解统计信息，使用`.describe()`方法

## 评估数据  

### 结构  
- 乱数据
- 整洁数据：每列是一个变量，每行是一个观察值，每个单元格是一个值

### 内容
- 脏数据（丢失数据、重复数据、不一致数据（混用）、无效或错误数据）
- 干净数据

先看`结构`
- 用`df1.info()`获取概况
- 获取开头/结尾N行，是否符合整洁数据要求，用`df1.head(n)`或者`df1.sample(n)`随机选择行，如果出现值或列展示不全，使用`pd.set_option(xxx)`调整上限

再看`内容`  
### 评估丢失数据
- 使用`df1.info()`评估丢失数据，将每列non-null的数量和rangeindex即行的数量进行对比
- 或者使用`isnull`方法（适用于Series和DF），即`series1.isnull().sum()`或`df1.isnull().sum()`，series返回一列中缺失值的情况，df返回每列中缺失值的情况（布尔值）。如果结果都为0，则无缺失值
- 提取丢失数据的行，使用`df1[df1[列名].isnull()]`本质上就是在获取符合条件（True）的行

### 评估重复数据  
- 使用`series1.duplicated()`或`df1.duplicated()`
- 由于DF的duplicated方法是查看两行是否完全一样，所以想指定检查某几个变量是否重复时，传入参数，即`df1.duplicated(subset=[列名1,列名2])`，只有规定的变量重复时，对应duplicated变量才是True
- 提取重复数据的行，同上面，即`df1[df1.duplicated(subset=[列名1,列名2])`

### 评估不一致数据  
- 使用`series1.value_counts()`

### 评估无效或错误数据  
- 使用`series1.sort_value()`或`df1.describe()`查看异常大或小值

## 清洗数据  
- 为了区分原始df和清洗后的df，先使用`df1 = df0.copy()`创建一个df0的副本df1

### CASE1 索引及列名乱（结构性问题1） 
- 针对索引，使用`df1.rename(index={旧索引:新索引})`
- 针对列名，使用`df1.rename(columns={旧列名：新列名})`
- 批量操作：`df1.rename(columns=某函数/某方法)` 或 `df1.rename(index = 某函数/方法)`
- 例如：`df1.rename(columns=str.upper)` 返回列名变成大写
- 使用Series的`str`属性，来获取包含很多字符串方法的类实例
- 把某列设置为索引`df1.set_index(列名)`
- `df1.reset_index()`把索引设置为初始默认位置索引，原本索引变成单独一列
- `df1.sort_index()` 排序索引
- 以上原始df都未改变，要重新赋值；或者传入`inplace=True`
![对字符串SERIES调用的更多方法](https://img.picui.cn/free/2025/06/01/683c46b936871.png)

### CASE2 数据内容乱（结构性问题2）
- 转置`df1 = df1.T`
### 把一列拆分为多列:
- 如果是字符串，使用`df1.[列名].str.split("分隔符"（可以是空格，/等等）,expand = True)`，返回一个包含多列的DF，之后使用`df1[[列名1,列名2]] = df1.[列名].str.split("分隔符"（可以是空格，/等等）,expand = True)`来添加列，再通过`df1 = df1.drop(原列名, axis = 1)`来删除原始列。
### 合并列：
- 使用`df1[列名1].str..cat(df[列名2],sep="指定拼接时的分隔符")`，之后再使用同上方的添加列和删除列的操作即可。  
### 把宽数据转换成长数据  
- `df1 = pd.melt(df1, di_vars=[不需要处理的列名], var_name=包含原本列名值的新列列名, value_name=包含原本 变量值的新列列名)`  
### 拆分行  
- `df1.explode(原列名)`
### 删除行或列  
- `df1 = .drop方法`  
注意：基本所有df操作都是不改变原始df的，使用重新赋值

### CASE3 数据内容性  
### 处理缺失数据  
- 使用`df1[列名]=值`赋值操作，对整列缺失值进行填充
- 使用`df1.loc[行名,列名]=值`，对某一特定缺失值进行填充
- 使用`df1.loc[切片]`方法对部分缺失值进行填充
- 使用`df1[列名].fillna(需传入的值)`对特定列中的缺失值进行填充
- 使用`df1.fillna(传入值或者一个字典，列名为键，需传入的值为值)`对整个df中的缺失值进行填充
- 以上不改变原始df
- 使用`df1.dropna(subset=[列名],axis=0)`返回去掉包含缺失值的行所组成的新的df，使用subset可以只检查对应的列下是否由缺失值，有则删除该行  
### 删除重复值  
- 使用`df1[列名].drop_duplicates()`或`df1.drop_duplicates(subset=[列名1,列名2])`删除指定重复行，默认删除第二次出现的行，使用`keep='last'`来删除第一次出现的行  
### 对值进行替换（处理不一致数据）  
- 使用`df1.replace(要被替换的值（可以传入列表）,替换成什么值（或者全部传成一个字典）,inplace=True)`  
### 对值的类型进行转换
- `series1.astype(类型名)`'str'=='object'
- 推荐对分类数据提前全部转换`series1.astype("category")`比如：性别，颜色，离散可数的数据
- 对于日期时间数据类型，使用`pd.to_datetime(要转换的列)`

## 保存数据  
- 写入csv文件
- `df1.to_csv(文件路径,index=True(False不保存索引))`将df1转成csv，同时保存到对应路径的文件里面，如果不存在，则会自动创建，如果原始文件存在，会覆盖
- 重新读取之前保存的文件，会出现索引单独成一列的状况，要先用`rename`方法，将那一列去一个有意义的名字，再使用`set_index`方法，把那一列设置为索引